### ISSUE TITLE
Send to RStudio

### ISSUE THREAD

**Issue by karthik** [wch/SendText#10]
I'm sort of ashamed to admit that I don't use RStudio much but lately seem to be enjoying it more (over just R from iterm). Would it consider adding RStudio as an additional target to the ones you already have?

**Comment by wch** [comment]
Sure, that sounds useful. I'm not sure how to do that cross-platform, though. On a Mac, you could use Applescript (or the new Javascript bindings), but I'm not sure how it would be done on Windows or Linux.

**Comment by karthik** [comment]
Good point. But no biggie. I'll hack something together temporarily for osx.

**Comment by vnijs** [comment]
@karthik Did you get this to work on osx?
